name         'joejulian-yum'
version      '2.0'
source       'git://github.com/joejulian/joejulian-yum.git'
author       'Marcel Härry, Simon Josi, Joe Julian'
license      'GPLv3'
summary      'Yum Puppet Module'
description  'This module manages the installation and removal of yum repositories.'
project_page 'http://github.com/joejulian/joejulian-yum'

dependency   'puppetlabs/stdlib', '>= 2.3.3'
